# Generated by Django 4.2.1 on 2023-05-31 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name': 'Notes',
                'verbose_name_plural': 'Notess',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('company', models.CharField(max_length=50)),
                ('flight_number', models.CharField(max_length=12)),
                ('f_from', models.CharField(max_length=12)),
                ('f_to', models.CharField(max_length=12)),
                ('stand', models.CharField(max_length=3)),
                ('carrier_reg', models.CharField(max_length=12)),
                ('carrier_type', models.CharField(max_length=12)),
                ('statues', models.CharField(choices=[('Arrival', 'Arrival'), ('Departure', 'Departure')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('observations', models.ManyToManyField(to='flight.notes')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
